name: api-url-map
defaultService: global/backendServices/api-lb-service
hostRules:
  - hosts:
      - '*'
    pathMatcher: method-matcher
pathMatchers:
  - name: method-matcher
    defaultService: global/backendServices/api-lb-service
    routeRules:
      - priority: 0
        matchRules:
          - prefixMatch: /ws
        service: global/backendServices/api-lb-service
      - priority: 1
        matchRules:
          # - regexMatch: '^\/(?!(?:ws|health)(?:\/|$)).*$'
          - headerMatches:
              - headerName: :method
                exactMatch: GET
          # - headerName: method
          # exactMatch: OPTIONS
        service: global/backendServices/api-lb-service
        routeAction:
          urlRewrite:
            hostRewrite: '{host}:8090'
          # weightedBackendServices:
          #   - backendService: global/backendServices/api-lb-service
          #     weight: 33
          #     routeAction:
          #       urlRewrite:
          #         hostRewrite: '{host}:8090'
          #   - backendService: global/backendServices/api-lb-service
          #     weight: 33
          #     urlRewrite:
          #       hostRewrite: '{host}:8090'
          #     hostRewrite: '{host}:8091'
          #   - backendService: global/backendServices/api-lb-service
          #     weight: 34
          #     hostRewrite: '{host}:8092'
